### ISSUE TITLE
 Sometimes it cannot start correctly under Windows operating system

### ISSUE THREAD

**Issue by yhz114514** [OwO-Network/DeepLX#155]
Sometimes it cannot be started correctly under the Windows operating system. The command line window of the program will close itself at the moment of startup. This problem is unstable and sometimes does not trigger, but it causes a lot of inconvenience.

**Comment by missuo** [comment]
I'm sorry, I don't have a Windows device to test. All four of my computers are Macs.

**Comment by infrost** [comment]
I've encountered this problem a few times.
This problem is likely due to **the port required by DeepLX is somehow not released properly**.
For windows, simply use `powershell/cmd` to run `netstat -ano | findstr :1188` (default port) to see any process taking that port, and try to terminate it.
If this problem persists, simply log out and back in or restart the computer.

In addition, sometimes some error will be shown in the command line window. You can use powershell command `./deeplx_windows_amd64.exe; Read-Host` in the program directory to prevent window from automatically closing to inspect it.

**Comment by infrost** [comment]
For most cases:
![image](https://github.com/user-attachments/assets/560137d8-5b64-460a-b1c6-51681bb6b46e)
then
![image](https://github.com/user-attachments/assets/1d84dcd0-1fb1-4a76-b6c7-f9eb832bbf60)

done.

**Comment by yhz114514** [comment]
好的，感谢指导
