### ISSUE TITLE
我想知道，这种方式，最多支持1秒调多少次， 不会被deepl封IP，封是永久封还是临时封？

### ISSUE THREAD

**Issue by asasas234** [OwO-Network/DeepLX#56]
如题，不知道作者是否有做过这方面的测试， 求分享

**Comment by missuo** [comment]
I haven't done a specific test, because different IPs may also have differences. For example, home broadband has higher security and the probability of being blocked may be smaller. In addition, DeepL's risk control strategy may have been changing. I guess it's out of my control, so I don't have to dig into it. What I want to say is that this project is completely sufficient for the translation of daily reading life. If you want to use this project to translate a whole book or a whole webpage in batches, I think it may not be able to do it.

Thank you for your interest in this project.
